#!/bin/bash
# Commands to run on EC2 for SSL setup

echo "📝 SSL Setup Commands for EC2"
echo "=============================="
echo ""
echo "1. SSH into EC2:"
echo "   ssh -i /Users/maverick/mayhouse/keys/mayhouse-backend-dev.pem ec2-user@ec2-18-223-166-226.us-east-2.compute.amazonaws.com"
echo ""
echo "2. Once logged in, edit the setup script to add your email:"
echo "   nano setup_ssl.sh"
echo "   Find line: --email your-email@example.com"
echo "   Change to: --email YOUR_REAL_EMAIL@example.com"
echo "   Save: Ctrl+O, Enter, Ctrl+X"
echo ""
echo "3. Run the SSL setup script:"
echo "   sudo ./setup_ssl.sh"
echo ""
echo "4. After SSL is set up, update backend .env:"
echo "   Find your backend directory (one of these):"
echo "   cd /home/ec2-user/backend"
echo "   OR: cd /opt/mayhouse/backend"
echo "   OR: cd ~/mayhouse-backend"
echo ""
echo "   Then edit .env:"
echo "   sudo nano .env"
echo ""
echo "   Update these lines:"
echo "   OAUTH_REDIRECT_URI=https://api.mayhouse.in/auth/oauth/google/callback"
echo "   CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,https://mayhouse.in,https://www.mayhouse.in"
echo ""
echo "   Save: Ctrl+O, Enter, Ctrl+X"
echo ""
echo "5. Restart backend:"
echo "   sudo systemctl restart mayhouse-backend"
echo "   OR: sudo docker restart mayhouse-backend-container"
echo ""
echo "6. Test it works:"
echo "   curl https://api.mayhouse.in/health/"
echo ""
echo "✅ If you see {\"status\":\"healthy\"}, SSL is working!"

