#!/bin/bash
# Script to update backend environment variables on EC2

echo "==================================="
echo "Backend Environment Update Script"
echo "==================================="
echo ""
echo "This script will guide you through updating the backend .env on EC2"
echo ""

# SSH command
SSH_KEY="/Users/maverick/mayhouse/keys/mayhouse-backend-dev.pem"
EC2_HOST="ec2-user@ec2-18-223-166-226.us-east-2.compute.amazonaws.com"

echo "Step 1: Finding backend directory..."
echo "--------------------------------------"
echo "Run these commands on EC2 to find your backend:"
echo ""
echo "ssh -i $SSH_KEY $EC2_HOST"
echo ""
echo "# Once logged in, try these locations:"
echo "ls -la ~/backend"
echo "ls -la ~/mayhouse-backend"
echo "ls -la /opt/mayhouse/backend"
echo ""

echo "Step 2: Update .env file"
echo "--------------------------------------"
echo "Once you've found the backend directory, edit the .env file:"
echo ""
echo "cd <backend-directory>"
echo "sudo nano .env"
echo ""
echo "Update these two lines:"
echo ""
echo "OAUTH_REDIRECT_URI=https://api.mayhouse.in/auth/oauth/google/callback"
echo "CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,https://mayhouse.in,https://www.mayhouse.in,https://mayhouse-git-main-tanishkhots-projects.vercel.app"
echo ""
echo "Save: Ctrl+O, Enter, Ctrl+X"
echo ""

echo "Step 3: Restart backend service"
echo "--------------------------------------"
echo "After saving the .env file, restart the backend:"
echo ""
echo "# If using systemd:"
echo "sudo systemctl restart mayhouse-backend"
echo "sudo systemctl status mayhouse-backend"
echo ""
echo "# OR if using Docker:"
echo "sudo docker restart mayhouse-backend-container"
echo "sudo docker ps | grep mayhouse"
echo ""

echo "Step 4: Verify"
echo "--------------------------------------"
echo "Test that the backend is working:"
echo ""
echo "curl https://api.mayhouse.in/health/"
echo ""
echo "Should return: {\"status\":\"healthy\",\"message\":\"Mayhouse Backend is running\"...}"
echo ""

