version: '3.8'

services:
  mayhouse-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Production optimizations
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
